site_name: PyDOE
site_description: Design of Experiments for Python
site_url: https://pydoe.github.io/pydoe/
docs_dir: docs
site_dir: build/docs

repo_name: pydoe/pydoe
repo_url: https://github.com/pydoe/pydoe

# Copyright
copyright: Copyright &copy; 2013–2025 PyDOE

# Configuration
theme:
  name: material
  language: en

  features:
    # content features
    - content.code.copy # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code+copy#code-copy-button
    - content.code.annotate # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations
    # navigation features
    - navigation.instant # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#instant-loading
    - navigation.instant.progress # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#progress-indicator
    - navigation.tracking # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#anchor-tracking
    - navigation.tabs # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#navigation-tabs
    - navigation.tabs.sticky # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#sticky-navigation-tabs
    - navigation.sections # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#navigation-sections
    - navigation.indexes # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#section-index-pages
    - toc.follow # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#anchor-following
    - navigation.top # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#back-to-top-button
    - navigation.footer # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-footer
    # search features
    - search.suggest # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search+highlight#search-suggestions
    - search.highlight # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search+highlight#search-highlighting
    - search.share # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search+highlight#search-sharing

  # Palette configuration
  palette:
    - scheme: default
      primary: blue grey
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Logo and favicon
  favicon: assets/images/pydoe.ico
  logo: assets/images/pydoe.png

  # Font configuration
  font:
    text: Roboto
    code: Roboto Mono

# Navigation structure
nav:
  - Get Started:
    - index.md
    - Installation: installation.md
    - Contributing: contributing.md
    - License: license.md
    - Credits: credits.md
    - Contributors: contributors.md
    - Users: users.md
  - Theory:
    - Introduction:
        - Overview: theory/introduction/index.md
        - Experimental Design: theory/introduction/what-is-doe.md
        - Uses of DOE: theory/introduction/doe-uses.md
        - Steps of DOE: theory/introduction/doe-steps.md
    - Assumptions:
        - Overview: theory/assumptions/index.md
        - Measurement System: theory/assumptions/measurement-system.md
        - Process Stability: theory/assumptions/process-stability.md
        - Simple Model: theory/assumptions/simple-model.md
        - Residuals: theory/assumptions/residuals.md
    - Choosing an Experimental Design:
        - Overview: theory/choosing-design/index.md
        - Set Objectives: theory/choosing-design/objectives.md
        - Select Process Variables: theory/choosing-design/process-variables.md
        - Select Experimental Design: theory/choosing-design/select-design.md
        - Completely Randomized Designs: theory/choosing-design/completely-randomized.md
        - Randomized Block Designs: theory/choosing-design/randomized-block.md
        - Latin Square Designs: theory/choosing-design/latin-squares.md
        - Graeco-Latin Square Designs: theory/choosing-design/graeco-latin-squares.md
        - Hyper-Graeco-Latin Square Designs: theory/choosing-design/hyper-graeco-latin-squares.md
        - Full Factorial Designs: theory/choosing-design/full-factorial.md
        - Two-Level Full Factorial Designs: theory/choosing-design/two-level-full-factorial.md
        - Full Factorial Example: theory/choosing-design/full-factorial-example-s3.md
        - Blocking of Full Factorial Designs: theory/choosing-design/blocking-full-factorial.md
        - Fractional Factorial Designs: theory/choosing-design/fractional-factorial.md
        - "A 2^(3-1) Half-Fraction Design": theory/choosing-design/half-fraction-design.md
        - Constructing the Half-Fraction Design: theory/choosing-design/constructing-half-fraction.md
        - Confounding (Aliasing): theory/choosing-design/confounding.md
        - Design Resolution: theory/choosing-design/design-resolution.md
        - Use of Fractional Factorial Designs: theory/choosing-design/using-fractional-factorial.md
        - Screening Designs: theory/choosing-design/screening-designs.md
        - Fractional Factorial Summary Tables: theory/choosing-design/fractional-factorial-tables.md
        - Plackett-Burman Designs: theory/choosing-design/plackett-burman.md
        - Response Surface Designs: theory/choosing-design/response-surface.md
        - Central Composite Designs: theory/choosing-design/central-composite.md
        - Box-Behnken Designs: theory/choosing-design/box-behnken.md
        - Comparisons of Response Surface Designs: theory/choosing-design/design-comparisons.md
        - Blocking a Response Surface Design: theory/choosing-design/blocking-rsd.md
        - Adding Center Points: theory/choosing-design/center-points.md
        - Improving Fractional Design Resolution: theory/choosing-design/improving-resolution.md
        - Mirror-Image Foldover Designs: theory/choosing-design/mirror-image-foldover.md
        - Alternative Foldover Designs: theory/choosing-design/alternative-foldover.md
        - Three-Level Full Factorial Designs: theory/choosing-design/three-level.md
        - Three-Level, Mixed Level and Fractional Factorial Designs: theory/choosing-design/mixed-level.md
    - Analysis of DOE Data:
        - Overview: theory/analysis-doe/index.md
        - DOE Analysis Steps: theory/analysis-doe/doe-analysis-steps.md
        - Plotting DOE Data: theory/analysis-doe/plotting-doe-data.md
        - Modeling DOE Data: theory/analysis-doe/modeling-doe-data.md
        - Testing and Revising Models: theory/analysis-doe/testing-revising-models.md
        - Interpreting DOE Results: theory/analysis-doe/interpreting-results.md
        - Confirming DOE Results: theory/analysis-doe/confirming-results.md
        - DOE Examples: theory/analysis-doe/doe-examples.md
        - Full Factorial Example: theory/analysis-doe/full-factorial-example.md
        - Fractional Factorial Example: theory/analysis-doe/fractional-factorial-example.md
        - Response Surface Example: theory/analysis-doe/response-surface-example.md
    - Advanced Topics:
        - Overview: theory/advanced-topics/index.md
        - When Classical Designs Don't Work: theory/advanced-topics/when-classical-fail.md
        - Computer-Aided Designs: theory/advanced-topics/computer-aided-designs.md
        - D-Optimal Designs: theory/advanced-topics/d-optimal.md
        - Repairing a Design: theory/advanced-topics/repairing-design.md
        - Optimizing a Process: theory/advanced-topics/optimizing-process.md
        - Single Response Case: theory/advanced-topics/single-response.md
        - Path of Steepest Ascent (Single): theory/advanced-topics/single-response-steepest-ascent.md
        - Confidence Region for Search Path: theory/advanced-topics/confidence-region.md
        - Choosing the Step Length: theory/advanced-topics/step-length.md
        - Optimization with Quadratic Fit: theory/advanced-topics/quadratic-fit-optimization.md
        - Effect of Sampling Error: theory/advanced-topics/sampling-error-effect.md
        - Constrained Optimization: theory/advanced-topics/constrained-optimization.md
        - Multiple Response Case: theory/advanced-topics/multiple-response.md
        - Path of Steepest Ascent (Multiple): theory/advanced-topics/multiple-response-steepest-ascent.md
        - Desirability Approach: theory/advanced-topics/multiple-response-desirability.md
        - Mathematical Programming Approach: theory/advanced-topics/multiple-response-math-programming.md
        - Mixture Designs: theory/advanced-topics/mixture-designs.md
        - Mixture Screening Designs: theory/advanced-topics/mixture-screening.md
        - Simplex-Lattice Designs: theory/advanced-topics/simplex-lattice.md
        - Simplex-Centroid Designs: theory/advanced-topics/simplex-centroid.md
        - Constrained Mixture Designs: theory/advanced-topics/constrained-mixture.md
        - Mixture and Process Variables Together: theory/advanced-topics/mixture-process-vars.md
        - Nested Variation: theory/advanced-topics/nested-variation.md
        - Taguchi Designs: theory/advanced-topics/taguchi-designs.md
        - John's 3/4 Fractional Factorial Designs: theory/advanced-topics/johns-34-designs.md
        - Small Composite Designs: theory/advanced-topics/small-composite-designs.md
        - An EDA Approach to Experiment Design: theory/advanced-topics/eda-approach.md
        - Ordered Data Plot: theory/advanced-topics/eda-ordered-data-plot.md
        - DOE Scatter Plot: theory/advanced-topics/eda-scatter-plot.md
        - DOE Mean Plot: theory/advanced-topics/eda-mean-plot.md
        - Interaction Effects Matrix Plot: theory/advanced-topics/eda-interaction-plot.md
        - Block Plot: theory/advanced-topics/eda-block-plot.md
        - DOE Youden Plot: theory/advanced-topics/eda-youden-plot.md
        - Effects Plot: theory/advanced-topics/eda-effects-plot.md
        - Statistical Significance: theory/advanced-topics/eda-effects-statistical.md
        - Engineering Significance: theory/advanced-topics/eda-effects-engineering.md
        - Numerical Significance: theory/advanced-topics/eda-effects-numerical.md
        - Pattern Significance: theory/advanced-topics/eda-effects-pattern.md
        - Half-Normal Probability Plot: theory/advanced-topics/eda-half-normal-plot.md
        - Cumulative Residual Standard Deviation Plot: theory/advanced-topics/eda-cumulative-ressd-plot.md
        - What is a Model?: theory/advanced-topics/eda-ressd-model.md
        - Goodness-of-fit Metric: theory/advanced-topics/eda-ressd-goodness.md
        - Constructing a Good Model: theory/advanced-topics/eda-ressd-good-model.md
        - When to Stop Adding Terms: theory/advanced-topics/eda-ressd-terms.md
        - Form of the Model: theory/advanced-topics/eda-ressd-form.md
        - Advantages of Linear Combinatoric Model: theory/advanced-topics/eda-ressd-advantages.md
        - Generating Predicted Values: theory/advanced-topics/eda-ressd-predicted.md
        - Using the Model Beyond the Data Domain: theory/advanced-topics/eda-ressd-domain.md
        - Best Confirmation Point: theory/advanced-topics/eda-ressd-confirmation.md
        - Interpolation: theory/advanced-topics/eda-ressd-interpolation.md
        - Extrapolation: theory/advanced-topics/eda-ressd-extrapolation.md
        - DOE Contour Plot: theory/advanced-topics/eda-contour-plot.md
        - Axes: theory/advanced-topics/eda-contour-axes.md
        - Contour Curves: theory/advanced-topics/eda-contour-curves.md
        - Optimal Response Value: theory/advanced-topics/eda-contour-optimal-value.md
        - Best Corner: theory/advanced-topics/eda-contour-best-corner.md
        - Steepest Ascent/Descent: theory/advanced-topics/eda-contour-steepest.md
        - Optimal Curve: theory/advanced-topics/eda-contour-optimal-curve.md
        - Optimal Setting: theory/advanced-topics/eda-contour-optimal-setting.md
    - Case Studies:
        - Overview: theory/case-studies/index.md
        - Eddy Current Probe Sensitivity Study: theory/case-studies/eddy-current.md
        - Background and Data: theory/case-studies/eddy-current-background.md
        - Initial Plots and Main Effects: theory/case-studies/eddy-current-initial-plots.md
        - Interaction Effects: theory/case-studies/eddy-current-interaction.md
        - Block Plots: theory/case-studies/eddy-current-block-plots.md
        - Estimate Effects: theory/case-studies/eddy-current-estimate-effects.md
        - Modeling and Prediction: theory/case-studies/eddy-current-modeling.md
        - Intermediate Conclusions: theory/case-studies/eddy-current-conclusions.md
        - Important Factors: theory/case-studies/eddy-current-important-factors.md
        - Validate the Model: theory/case-studies/eddy-current-validate.md
        - Using the Model: theory/case-studies/eddy-current-using-model.md
        - Conclusions and Next Step: theory/case-studies/eddy-current-next-step.md
        - Work This Example Yourself: theory/case-studies/eddy-current-work-yourself.md
        - Sonoluminescent Light Intensity Study: theory/case-studies/sonoluminescent.md
        - Background and Data (Sono): theory/case-studies/sono-background.md
        - Initial Plots and Main Effects (Sono): theory/case-studies/sono-initial-plots.md
        - Interaction Effects (Sono): theory/case-studies/sono-interaction.md
        - Block Plots (Sono): theory/case-studies/sono-block-plots.md
        - Youden Plot: theory/case-studies/sono-youden-plot.md
        - "|Effects| Plot": theory/case-studies/sono-effects-plot.md
        - Half-Normal Probability Plot: theory/case-studies/sono-half-normal.md
        - Cumulative Residual SD Plot: theory/case-studies/sono-cumulative-ressd.md
        - DOE Contour Plot: theory/case-studies/sono-contour-plot.md
        - Summary of Conclusions: theory/case-studies/sono-conclusions.md
        - Work This Example Yourself (Sono): theory/case-studies/sono-work-yourself.md
    - Glossary:
        - A Glossary of DOE Terminology: theory/glossary/index.md
    - References:
        - References: theory/references/index.md
  - Reference:
    - Factorial Designs: reference/factorial.md
    - Response Surface Designs: reference/response_surface.md
    - Mixture Designs: reference/mixture.md
    - Randomized Designs: reference/randomized.md
    - Low-Discrepancy Sequences: reference/low_discrepancy_sequences.md
    - Sampling Designs: reference/sampling_designs.md
    - Taguchi Designs: reference/taguchi.md
    - Optimal Designs: reference/doe_optimal.md
    - Sparse Grid Designs: reference/sparse_grid.md
    - Specialized Designs: reference/specialized.md
    - Sequential Designs: reference/sequential.md
  - Changelog: changelog.md

plugins:
  - search: # https://squidfunk.github.io/mkdocs-material/plugins/search
  - minify: # https://github.com/byrnereese/mkdocs-minify-plugin
      minify_html: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_css:    # https://squidfunk.github.io/mkdocs-material/customization/#additional-css
  - assets/stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pydoe/pydoe
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pydoe/

extra_javascript:
  - assets/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: relative_to_docs
    unrecognized_links: warn
