site_name: PyDOE
site_description: Design of Experiments for Python
site_url: https://pydoe.github.io/pydoe/
docs_dir: docs
site_dir: build/docs

repo_name: pydoe/pydoe
repo_url: https://github.com/pydoe/pydoe

# Copyright
copyright: Copyright &copy; 2013–2025 PyDOE

# Configuration
theme:
  name: material
  language: en

  features:
    # content features
    - content.code.copy # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code+copy#code-copy-button
    - content.code.annotate # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations
    # navigation features
    - navigation.instant # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#instant-loading
    - navigation.instant.progress # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#progress-indicator
    - navigation.tracking # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#anchor-tracking
    - navigation.tabs # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#navigation-tabs
    - navigation.tabs.sticky # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#sticky-navigation-tabs
    - navigation.sections # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#navigation-sections
    - navigation.indexes # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#section-index-pages
    - toc.follow # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#anchor-following
    - navigation.top # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#back-to-top-button
    - navigation.footer # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-footer
    # search features
    - search.suggest # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search+highlight#search-suggestions
    - search.highlight # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search+highlight#search-highlighting
    - search.share # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search+highlight#search-sharing

  # Palette configuration
  palette:
    - scheme: default
      primary: blue grey
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Logo and favicon
  favicon: assets/images/pydoe.ico
  logo: assets/images/pydoe.png

  # Font configuration
  font:
    text: Roboto
    code: Roboto Mono

# Navigation structure
nav:
  - Get Started:
    - index.md
    - Installation: installation.md
    - Contributing: contributing.md
    - License: license.md
    - Credits: credits.md
    - Contributors: contributors.md
    - Users: users.md
  - Theory:
    - Introduction:
        - Overview: theory/introduction/index.md
        - Experimental Design: theory/introduction/what-is-doe.md
        - Uses of DOE: theory/introduction/doe-uses.md
        - Steps of DOE: theory/introduction/doe-steps.md
    - Assumptions:
        - Overview: theory/assumptions/index.md
        - Measurement System: theory/assumptions/measurement-system.md
        - Process Stability: theory/assumptions/process-stability.md
        - Simple Model: theory/assumptions/simple-model.md
        - Residuals: theory/assumptions/residuals.md
    - Choosing an Experimental Design:
        - Overview: theory/choosing-design/index.md
        - Set Objectives: theory/choosing-design/objectives.md
        - Select Process Variables: theory/choosing-design/process-variables.md
        - Select Experimental Design: theory/choosing-design/select-design.md
        - Completely Randomized Designs: theory/choosing-design/completely-randomized.md
        - Randomized Block Designs: theory/choosing-design/randomized-block.md
        - Full Factorial Designs: theory/choosing-design/full-factorial.md
        - Fractional Factorial Designs: theory/choosing-design/fractional-factorial.md
        - Plackett-Burman Designs: theory/choosing-design/plackett-burman.md
        - Response Surface Designs: theory/choosing-design/response-surface.md
        - Central Composite Designs: theory/choosing-design/central-composite.md
        - Box-Behnken Designs: theory/choosing-design/box-behnken.md
        - Comparisons of Response Surface Designs: theory/choosing-design/design-comparisons.md
        - Blocking a Response Surface Design: theory/choosing-design/blocking-rsd.md
        - Adding Center Points: theory/choosing-design/center-points.md
        - Improving Fractional Design Resolution: theory/choosing-design/improving-resolution.md
        - Three-Level Full Factorial Designs: theory/choosing-design/three-level.md
        - Three-Level, Mixed Level and Fractional Factorial Designs: theory/choosing-design/mixed-level.md
    - Analysis of DOE Data:
        - Overview: theory/analysis-doe/index.md
        - DOE Analysis Steps: theory/analysis-doe/doe-analysis-steps.md
        - Plotting DOE Data: theory/analysis-doe/plotting-doe-data.md
        - Modeling DOE Data: theory/analysis-doe/modeling-doe-data.md
        - Testing and Revising Models: theory/analysis-doe/testing-revising-models.md
        - Interpreting DOE Results: theory/analysis-doe/interpreting-results.md
        - Confirming DOE Results: theory/analysis-doe/confirming-results.md
        - DOE Examples: theory/analysis-doe/doe-examples.md
        - Full Factorial Example: theory/analysis-doe/full-factorial-example.md
        - Fractional Factorial Example: theory/analysis-doe/fractional-factorial-example.md
        - Response Surface Example: theory/analysis-doe/response-surface-example.md
    - Advanced Topics:
        - Overview: theory/advanced-topics/index.md
        - When Classical Designs Don't Work: theory/advanced-topics/when-classical-fail.md
        - Computer-Aided Designs: theory/advanced-topics/computer-aided-designs.md
        - D-Optimal Designs: theory/advanced-topics/d-optimal.md
        - Repairing a Design: theory/advanced-topics/repairing-design.md
        - Optimizing a Process: theory/advanced-topics/optimizing-process.md
        - Single Response Case: theory/advanced-topics/single-response.md
        - Multiple Response Case: theory/advanced-topics/multiple-response.md
  - Reference:
    - Factorial Designs: reference/factorial.md
    - Response Surface Designs: reference/response_surface.md
    - Mixture Designs: reference/mixture.md
    - Randomized Designs: reference/randomized.md
    - Low-Discrepancy Sequences: reference/low_discrepancy_sequences.md
    - Sampling Designs: reference/sampling_designs.md
    - Taguchi Designs: reference/taguchi.md
    - Optimal Designs: reference/doe_optimal.md
    - Sparse Grid Designs: reference/sparse_grid.md
    - Specialized Designs: reference/specialized.md
  - Changelog: changelog.md

plugins:
  - search: # https://squidfunk.github.io/mkdocs-material/plugins/search
  - minify: # https://github.com/byrnereese/mkdocs-minify-plugin
      minify_html: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_css:    # https://squidfunk.github.io/mkdocs-material/customization/#additional-css
  - assets/stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pydoe/pydoe
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pydoe/

extra_javascript:
  - assets/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: relative_to_docs
    unrecognized_links: warn
