"""
This module implements the Faure sequence, a low-discrepancy
quasirandom sequence used in numerical integration, sampling,
and global optimization tasks.

The Faure sequence generates points in a unit hypercube [0, 1]^d
using a single prime base shared across all dimensions, combined
with a Pascal-matrix (binomial coefficient) digit permutation that
is applied independently in each dimension. This makes the Faure
sequence particularly attractive in moderate to high dimensions,
since (unlike the Halton sequence) it does not require a different
prime base per dimension.

For a given dimension `s`, the base `b` is chosen as the smallest
prime number greater than or equal to `max(s, 2)`. Each coordinate
of point `n` is obtained by expanding `n` in base `b`, applying a
binomial-coefficient transformation (raised to successive powers of
the dimension index) to the digits modulo `b`, and then performing a
radical inversion.

References
----------
Faure, H. (1982). "Discrépance de suites associées à un système de
numération (en dimension s)." *Acta Arithmetica*, 41(4), 337-351.
"""

import math

import numpy as np


__all__ = ["faure_sequence"]


def faure_sequence(
    num_points: int, dimension: int, skip: int = 0
) -> np.ndarray:
    """
    Generate a Faure sequence in a given dimension.

    The Faure sequence is a low-discrepancy, quasi-random point set
    commonly used in numerical integration, sampling, and global
    optimization. A single prime base `b` (the smallest prime number
    greater than or equal to ``max(dimension, 2)``) is used for every
    dimension. Each coordinate is generated by expanding the sequence
    index in base `b`, transforming its digits with a binomial
    coefficient (Pascal) matrix raised to powers of the dimension
    index, and applying radical inversion.

    Parameters
    ----------
    num_points : int
        Number of points to generate in the sequence.
    dimension : int
        Number of dimensions (features) of the sequence.
    skip : int, optional
        Number of initial points in the sequence to skip. Default is 0.

    Returns
    -------
    points : ndarray of shape (`num_points`, `dimension`)
        The generated Faure sequence points.

    Raises
    ------
    ValueError
        If `num_points` is less than 1, `dimension` is less than 1,
        or `skip` is negative.

    Examples
    --------
    >>> faure_sequence(4, 2)
    array([[0.  , 0.  ],
           [0.5 , 0.5 ],
           [0.25, 0.75],
           [0.75, 0.25]])

    >>> faure_sequence(5, 1)
    array([[0.   ],
           [0.5  ],
           [0.25 ],
           [0.75 ],
           [0.125]])
    """
    if num_points < 1:
        raise ValueError(f"num_points must be at least 1, got {num_points}")
    if dimension < 1:
        raise ValueError(f"dimension must be at least 1, got {dimension}")
    if skip < 0:
        raise ValueError(f"skip must be non-negative, got {skip}")

    base = _smallest_prime_at_least(max(dimension, 2))

    num_digits = 1
    while base**num_digits <= num_points + skip:
        num_digits += 1

    pascal = _pascal_matrix_mod(num_digits, base)

    samples = np.empty((num_points, dimension), dtype=np.float64)

    for idx in range(num_points):
        n = idx + skip

        digits = [0] * num_digits
        remainder = n
        for k in range(num_digits):
            remainder, digits[k] = divmod(remainder, base)

        for d in range(dimension):
            value = 0.0
            for i in range(num_digits):
                transformed = 0
                for k in range(i, num_digits):
                    transformed += pascal[k][i] * (d ** (k - i)) * digits[k]
                transformed %= base
                value += transformed * base ** -(i + 1)
            samples[idx, d] = value

    return samples


def _pascal_matrix_mod(size: int, base: int) -> list:
    """
    Build a binomial coefficient (Pascal) matrix modulo `base`.

    Parameters
    ----------
    size : int
        The number of rows and columns of the square matrix.
    base : int
        The modulus to apply to each binomial coefficient.

    Returns
    -------
    matrix : list of list of int
        A `size` by `size` lower-triangular matrix where entry
        ``[k][i]`` is ``comb(k, i) % base`` for ``i <= k``, and 0
        otherwise.
    """
    matrix = [[0] * size for _ in range(size)]
    for k in range(size):
        for i in range(k + 1):
            matrix[k][i] = math.comb(k, i) % base

    return matrix


def _smallest_prime_at_least(n: int) -> int:
    """
    Find the smallest prime number greater than or equal to `n`.

    Parameters
    ----------
    n : int
        The lower bound to search from.

    Returns
    -------
    prime : int
        The smallest prime number that is greater than or equal to `n`.
    """
    candidate = max(n, 2)
    while not _is_prime(candidate):
        candidate += 1

    return candidate


def _is_prime(n: int) -> bool:
    """
    Check whether a number is prime.

    Parameters
    ----------
    n : int
        The number to check.

    Returns
    -------
    is_prime : bool
        True if `n` is a prime number, False otherwise.
    """
    if n < 2:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    for i in range(3, int(n**0.5) + 1, 2):
        if n % i == 0:
            return False

    return True
