"""
This module implements a Niederreiter-type digital sequence, a
base-2 low-discrepancy quasirandom sequence used in numerical
integration, sampling, and global optimization tasks.

The sequence is constructed as a digital (t, m, s)-net over GF(2):
for each dimension a generating matrix is built from the binary
linear-feedback-shift-register (LFSR) sequence associated with a
primitive polynomial over GF(2). Given the binary expansion of the
sequence index `n`, multiplying it (mod 2) by the generating matrix
of a dimension produces the binary digits of the radical-inverse
coordinate for that dimension.

Each dimension uses its own primitive polynomial over GF(2), so
different dimensions are generated by different LFSR sequences,
which keeps the resulting coordinates from being correlated.

References
----------
Niederreiter, H. (1988). "Low-discrepancy and low-dispersion
sequences." *Journal of Number Theory*, 30(1), 51-70.
https://doi.org/10.1016/0022-314X(88)90025-X

Bratley, P., & Fox, B. L. (1988). "Algorithm 659: Implementing
Sobol's quasirandom sequence generator." *ACM Transactions on
Mathematical Software*, 14(1), 88-100.
https://doi.org/10.1145/42288.214372
"""

import numpy as np


__all__ = ["niederreiter_sequence"]


# Primitive polynomials over GF(2), one per dimension (index 0
# corresponds to dimension 1, index 19 to dimension 20). Each entry
# is ``(degree, taps)`` where ``taps`` encodes the recurrence
# coefficients c_0, ..., c_{degree-1} (bit i of ``taps`` is c_i) of
# the primitive polynomial
# ``x**degree + c_{degree-1} * x**(degree-1) + ... + c_0``.
# Every entry below has been verified to define a maximal-length
# LFSR, i.e. the associated binary sequence has period
# ``2**degree - 1``.
_PRIMITIVE_POLYS = [
    (2, 0b11),
    (3, 0b11),
    (3, 0b101),
    (4, 0b11),
    (4, 0b1001),
    (5, 0b101),
    (5, 0b1001),
    (6, 0b11),
    (6, 0b11011),
    (7, 0b11),
    (7, 0b1001),
    (7, 0b1111),
    (8, 0b11101),
    (8, 0b101011),
    (9, 0b10001),
    (9, 0b11011),
    (10, 0b1001),
    (10, 0b11011),
    (11, 0b101),
    (11, 0b10111),
]


def niederreiter_sequence(
    num_points: int, dimension: int, n_bits: int = 30
) -> np.ndarray:
    """
    Generate a Niederreiter-type digital sequence.

    The sequence is a digital (t, m, s)-net over GF(2): for each
    dimension a binary generating matrix is derived from the LFSR
    sequence of a primitive polynomial over GF(2). The binary
    expansion of the point index `n` is mapped through this matrix
    (mod 2) to obtain the binary digits of the coordinate value.

    Up to 20 dimensions are supported, each backed by its own
    verified primitive polynomial over GF(2).

    Parameters
    ----------
    num_points : int
        Number of points to generate. Must be >= 1. For proper
        low-discrepancy behavior `num_points` should not exceed
        ``2 ** n_bits``, although larger values are accepted.
    dimension : int
        Number of dimensions of the sequence. Must be between 1
        and 20 (inclusive).
    n_bits : int, optional
        Number of bits of precision used for the generating
        matrices and the binary expansion of each coordinate.
        Must be >= 2. Default is 30.

    Returns
    -------
    points : ndarray of shape (`num_points`, `dimension`)
        The generated sequence points, with values in [0, 1).

    Raises
    ------
    ValueError
        If `num_points` < 1, `dimension` < 1, `dimension` > 20, or
        `n_bits` < 2.

    Examples
    --------
    >>> niederreiter_sequence(4, 2)
    array([[0.        , 0.        ],
           [0.42857143, 0.18110236],
           [0.85714286, 0.36220472],
           [0.71428571, 0.4488189 ]])

    >>> niederreiter_sequence(4, 2, n_bits=4)
    array([[0.    , 0.    ],
           [0.375 , 0.125 ],
           [0.8125, 0.3125],
           [0.6875, 0.4375]])
    """
    if num_points < 1:
        raise ValueError("num_points must be at least 1")
    if dimension < 1:
        raise ValueError("dimension must be at least 1")
    if dimension > 20:
        raise ValueError(
            "dimension must be at most 20 (the table of primitive "
            "polynomials only covers dimensions 1 through 20)"
        )
    if n_bits < 2:
        raise ValueError("n_bits must be at least 2")

    matrices = [
        _generating_matrix(degree, taps, n_bits)
        for degree, taps in _PRIMITIVE_POLYS[:dimension]
    ]

    points = np.empty((num_points, dimension), dtype=np.float64)
    weights = 2.0 ** -(np.arange(n_bits, dtype=np.float64) + 1.0)

    for n in range(num_points):
        bits = np.array([(n >> k) & 1 for k in range(n_bits)], dtype=np.uint8)
        for j, matrix in enumerate(matrices):
            digits = (matrix @ bits) % 2
            points[n, j] = np.dot(digits, weights)

    return points


def _lfsr_sequence(degree: int, taps: int, length: int) -> list:
    """
    Generate a binary LFSR sequence from a primitive polynomial.

    Parameters
    ----------
    degree : int
        Degree of the primitive polynomial over GF(2).
    taps : int
        Bitmask encoding the recurrence coefficients c_0, ...,
        c_{degree-1} (bit `i` is c_i).
    length : int
        Number of terms of the sequence to generate.

    Returns
    -------
    sequence : list of int
        The first `length` terms of the binary LFSR sequence.
    """
    sequence = [0] * (degree - 1) + [1]
    for k in range(degree, length):
        value = 0
        for i in range(degree):
            if (taps >> i) & 1:
                value ^= sequence[k - degree + i]
        sequence.append(value)

    return sequence[:length]


def _generating_matrix(degree: int, taps: int, n_bits: int) -> np.ndarray:
    """
    Build the binary generating matrix for one dimension.

    The matrix is a Hankel-style matrix built from the LFSR
    sequence of the given primitive polynomial, with
    ``matrix[r, k] = sequence[r + k]``.

    Parameters
    ----------
    degree : int
        Degree of the primitive polynomial over GF(2).
    taps : int
        Bitmask encoding the recurrence coefficients of the
        primitive polynomial.
    n_bits : int
        Size of the (square) generating matrix.

    Returns
    -------
    matrix : ndarray of shape (`n_bits`, `n_bits`)
        The binary generating matrix, with dtype ``np.uint8``.
    """
    sequence = _lfsr_sequence(degree, taps, 2 * n_bits)
    matrix = np.empty((n_bits, n_bits), dtype=np.uint8)
    for r in range(n_bits):
        for k in range(n_bits):
            matrix[r, k] = sequence[r + k]

    return matrix
